@startuml
<style>
    element {
        MinimumWidth 100
        MaximumWidth 180
    }
    .kondisi {
        FontSize 9
        Padding 5
        LineStyle 2
        BackGroundColor transparent
        HorizontalAlignment center
    }
</style>
skinparam defaultFontName "verdana"
start
:recordId_Acc = "001dM000002F6C8QAK";<<input>>
:varS_Input = ""Input Baru"";<<input>>

:cur_Acc 
----
select top1 from Account 
where Id EqualTo recordId_Acc
AND CreatedDate IsNull undefined;
:rst_Opty 
----
select * from Opportunity 
where AccountId EqualTo recordId_Acc
AND CreatedDate IsNull undefined;
switch (cek_Karyawan)
case (Big_Size)
	:Big Size
....
cur_Acc.NumberOfEmployees GreaterThan 7000.0
cur_Acc.IsDeleted EqualTo undefined;<<kondisi>>
	:varS_Rating = "Hot";
:varS_Output = "Hotter";
	:set_Hot_Amount(transforms)  --> rst_Contact;
case (Medium_Size)
	:Medium Size
....
cur_Acc.NumberOfEmployees GreaterThan 3000.0
cur_Acc.IsDeleted EqualTo undefined;<<kondisi>>
	:varS_Rating = "Warm";
:varS_Output = "Warmer";
	:set_Warm_Amount(transforms)  --> cek_Amount;
	switch (cek_Amount)
case (Keren)
	:Keren
....
set_Warm_Amount GreaterThan 4000.0;<<kondisi>>
	:varS_Output = "Warmer Keren";
case (Biasa)
	:Biasa;<<kondisi>>
endswitch
case (Small Size)
	:Small Size;<<kondisi>>
	:varS_Rating = "Cold";
:varS_Output = "Colder";
	:set_Cold_Amount(transforms)  --> rst_Contact;
endswitch
:rst_Contact 
----
select * from Contact 
where AccountId EqualTo cur_Acc.Id;
while(c : rst_Contact)
	:c.IsPriorityRecord = "true";
endwhile
:Update 
----
rst_Contact;
:Update Account 
----
Set BillingCity = Medan, Rating = varS_Rating
where 
Id = recordId_Acc;
:Upsert Account 
----
Set Name = Jimmy,
Type = cur_Acc.Type
----
on conflict (Name);
:varS_Output;<<output>>
:varS_Rating;<<output>>
stop
@enduml