@startuml
<style>
    element {
        MinimumWidth 100
        MaximumWidth 180
    }
    .kondisi {
        FontSize 9
        Padding 5
        LineStyle 2
        BackGroundColor transparent
        HorizontalAlignment center
    }
</style>
skinparam defaultFontName "verdana"
start
:start(start)  --> undefined;
:cur_Acc(recordLookups)  --> undefined;
:rst_Opty(recordLookups)  --> undefined;
switch (cek_Karyawan)
case (Big_Size)
:Big_Size(rules)  --> undefined;
:set_Rating_Hot(assignments)  --> undefined;
:set_Hot_Amount(transforms)  --> undefined;
:rst_Contact(recordLookups)  --> undefined;
:c(loops)  --> undefined;
case (Medium_Size)
:Medium_Size(rules)  --> undefined;
:set_Rating_Warm(assignments)  --> undefined;
:set_Warm_Amount(transforms)  --> undefined;
switch (cek_Amount)
case (Keren)
:Keren(rules)  --> undefined;
:set_Output(assignments)  --> undefined;
:rst_Contact(recordLookups)  --> c;
:c(loops)  --> end;
case (Biasa)
:Biasa(rules)  --> undefined;
:rst_Contact(recordLookups)  --> c;
:c(loops)  --> end;
endswitch
:rst_Contact(recordLookups)  --> c;
:c(loops)  --> end;
case (Small Size)
:Small Size(rules)  --> undefined;
:set_Rating_Cold(assignments)  --> undefined;
:set_Cold_Amount(transforms)  --> undefined;
:rst_Contact(recordLookups)  --> c;
:c(loops)  --> end;
endswitch
:set_Rating_Cold(assignments)  --> set_Cold_Amount;
:set_Cold_Amount(transforms)  --> rst_Contact;
:rst_Contact(recordLookups)  --> c;
:c(loops)  --> end;
stop
@enduml